# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uniquep.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 458)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 20, 491, 34))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search_input = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_input.setFont(font)
        self.search_input.setObjectName("search_input")
        self.gridLayout_2.addWidget(self.search_input, 0, 0, 1, 1)
        self.search_btn = QtWidgets.QPushButton(self.widget)
        self.search_btn.setStyleSheet("")
        self.search_btn.setObjectName("search_btn")
        self.gridLayout_2.addWidget(self.search_btn, 0, 1, 1, 1)
        self.download_btn = QtWidgets.QPushButton(self.widget)
        self.download_btn.setObjectName("download_btn")
        self.gridLayout_2.addWidget(self.download_btn, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(30, 20, 441, 361))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.upload_btn = QtWidgets.QPushButton(self.widget1)
        self.upload_btn.setObjectName("upload_btn")
        self.gridLayout.addWidget(self.upload_btn, 2, 1, 1, 1)
        self.upload_input = QtWidgets.QPlainTextEdit(self.widget1)
        self.upload_input.setObjectName("upload_input")
        self.gridLayout.addWidget(self.upload_input, 0, 0, 1, 2)
        self.select_file_btn = QtWidgets.QPushButton(self.widget1)
        self.select_file_btn.setObjectName("select_file_btn")
        self.gridLayout.addWidget(self.select_file_btn, 2, 0, 1, 1)
        self.upload_file_label = QtWidgets.QLabel(self.widget1)
        self.upload_file_label.setObjectName("upload_file_label")
        self.gridLayout.addWidget(self.upload_file_label, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "uniquep"))
        self.search_input.setText(_translate("Form", "dfdfsfdsfsfsd"))
        self.search_btn.setText(_translate("Form", "search"))
        self.download_btn.setText(_translate("Form", "download"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "up search"))
        self.upload_btn.setText(_translate("Form", "upload"))
        self.upload_input.setPlainText(_translate("Form", "csv"))
        self.select_file_btn.setText(_translate("Form", "select file"))
        self.upload_file_label.setText(_translate("Form", "xxx.file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "up upload"))
